# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1281, 626)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/application_picture/resource/application_picture/app_icon-round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.layout_dialog_main = QtWidgets.QHBoxLayout(Dialog)
        self.layout_dialog_main.setContentsMargins(0, 0, 0, 0)
        self.layout_dialog_main.setSpacing(0)
        self.layout_dialog_main.setObjectName("layout_dialog_main")
        self.widget_style_sheet = QtWidgets.QWidget(Dialog)
        self.widget_style_sheet.setStyleSheet("\n"
"   QWidget{\n"
"    font: 6pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(33, 37, 43);\n"
"    color: rgb(208, 208, 208);\n"
"    font-size: 10pt;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
" QScrollBar {\n"
"border: none;                                                /* без границ */\n"
"    border-right:5px solid rgb(211, 211, 211);;    /* С правой красной раницей */\n"
" }\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/* Ползунок */\n"
" QScrollBar::handle:vertical {    \n"
"    background:rgb(255, 255, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
"/*Нижняя стрелка*/\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/*Верхняя стрелка*/\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/* Цвета нижних и верхних стрелок */\n"
" QScrollBar::up-arrow:vertical{\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
" }\n"
"QScrollBar::down-arrow:vertical{\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(255, 255, 255);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QRadioButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"}\n"
"/* срабатывает, при нажатии*/\n"
"QRadioButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color:  rgb(0, 0, 0);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox */\n"
"/* Стандартное состояние*/\n"
"QCheckBox{\n"
"    padding-left: 8px;        /* Отступ слева */\n"
"    padding-right: -8px;    /* Отступ справа */\n"
"}\n"
"\n"
"/* Состояние - не выбран*/\n"
"QCheckBox::indicator:unchecked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/multi_check_box/resource/multi_check_box_svg/no_24dp.svg);\n"
"}\n"
"\n"
"/* Состояние -  выбран*/\n"
"QCheckBox::indicator:checked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/multi_check_box/resource/multi_check_box_svg/yes_green_24dp.svg);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QPushButton */\n"
"/*Стандартное состояние для кнопки*/\n"
"QPushButton {\n"
"    font-size: 12pt;\n"
"    background-color:rgb(37, 41, 48);/* задает цвет фона */\n"
"    display: inline-block;                            /* пределяет, будет ли элемент обрабатываться как блочный или встроенный элемент */\n"
"    border: 1px solid rgb(52, 59, 72);        /* задает границу элемента */\n"
"\n"
"    /* задает иконку */\n"
"    background-position: left center;                            /* выравнивание иконки */\n"
"    background-repeat: no-repeat;                                /* повторять иконку */\n"
"} \n"
"\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QPushButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"    border: none;                                                /* без границ */\n"
"    border-left:4px solid rgb(208, 208, 208);    /* С правой красной раницей */\n"
"}\n"
"\n"
"\n"
"/* срабатывает, при нажатии*/\n"
"QPushButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color: rgb(181, 181, 181);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"\n"
"/*Нейронная сеть*/\n"
"#pushButton_neural_network_heade{\n"
"    image: url(:/general_black_ui/resource/general_black_ui/network_24dp_white.svg);\n"
"    image-position: left center;\n"
"    padding-top: 2px; /* Отступ сверху */\n"
"    padding-bottom: 2px; /* Отступ снизу */\n"
"    padding-left: 4px; /* Отступ слева для симметрии */\n"
"}\n"
"#pushButton_reading_file_neural_network{image: url(:/general_black_ui/resource/general_black_ui/download_24dp_white.svg);}\n"
"#pushButton_reading_file_neural_network{border: none;}\n"
"\n"
"/*Данные*/\n"
"#pushButton_data_header {\n"
"    image: url(:/general_black_ui/resource/general_black_ui/data_24dp_white.svg);\n"
"    image-position: left center;\n"
"    padding-top: 2px; /* Отступ сверху */\n"
"    padding-bottom: 2px; /* Отступ снизу */\n"
"    padding-left: 4px; /* Отступ слева для симметрии */\n"
"}\n"
"#pushButton_reading_file_no_gas{image: url(:/general_black_ui/resource/general_black_ui/download_24dp_white.svg);}\n"
"#pushButton_reading_file_no_gas{border: none;}\n"
"#pushButton_reading_file_with_gas{image: url(:/general_black_ui/resource/general_black_ui/download_24dp_white.svg);}\n"
"#pushButton_reading_file_with_gas{border: none;}\n"
"\n"
"#radioButton_selected_range {\n"
"    image: url(:/general_black_ui/resource/general_black_ui/cycle1_24dp_white.svg);\n"
"    image-position: right center;\n"
"    padding-top: 3px; /* Отступ сверху */\n"
"    padding-bottom: 3px; /* Отступ снизу */\n"
"    padding-right: 4px; /* Отступ справа для симметрии */\n"
"} \n"
"#radioButton_selected_range:pressed      {\n"
"    image: url(:/general_black_ui/resource/general_black_ui/cycle2_24dp_white.svg);\n"
"    image-position: right center;\n"
"    padding-top: 3px; /* Отступ сверху */\n"
"    padding-bottom: 3px; /* Отступ снизу */\n"
"    padding-right: 4px; /* Отступ справа для симметрии */\n"
"}\n"
"\n"
"#pushButton_close_open_table {\n"
"    image: url(:/general_black_ui/resource/general_black_ui/table_24dp_white.svg);\n"
"    image-position: left center;\n"
"    padding-top: 2px; /* Отступ сверху */\n"
"    padding-bottom: 2px; /* Отступ снизу */\n"
"    padding-left: 4px; /* Отступ слева для симметрии */\n"
"}\n"
"\n"
"#pushButton_menu_calculate{\n"
"    image: url(:/general_black_ui/resource/general_black_ui/launch_24dp_white.svg);\n"
"    image-position: left center;\n"
"    padding-top: 2px; /* Отступ сверху */\n"
"    padding-bottom: 2px; /* Отступ снизу */\n"
"    padding-left: 4px; /* Отступ слева для симметрии */\n"
"}\n"
"\n"
"#pushButton_save_table_to_file{\n"
"    image: url(:/general_black_ui/resource/general_black_ui/save_24dp_white.svg);\n"
"    image-position: left center;\n"
"    padding-top: 2px; /* Отступ сверху */\n"
"    padding-bottom: 2px; /* Отступ снизу */\n"
"    padding-left: 4px; /* Отступ слева для симметрии */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit */\n"
"/* Стиль по умолчанию */\n"
"QLineEdit:enabled{\n"
"    background-color:rgb(44, 49, 58); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"}\n"
"\n"
"/* Если поле отключено */\n"
"QLineEdit:disabled {\n"
"    background-color:  rgba(67, 74, 88, 0); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"    color: rgb(67, 74, 88);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QGroupBox */\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);    /* задает цвет шрифта */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"\n"
"QTableWidget {    \n"
"    gridline-color: rgb(136, 136, 136);\n"
"    border-top: 1px solid rgb(54, 60, 74);\n"
"    border-bottom: 1px solid  rgb(54, 60, 74);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(72, 81, 94);\n"
"}\n"
"QHeaderView { qproperty-defaultAlignment: AlignCenter; }\n"
"/*Цвет верхнего и левого поля*/\n"
"QHeaderView::section{\n"
"    background-color:rgb(37, 41, 48);\n"
"    border-style: none;\n"
"border: 1px solid rgb(136, 136, 136);\n"
"}\n"
"/*Кнопка в верхнем левом углу*/\n"
"QTableCornerButton::section {background-color:rgb(33, 37, 43); }")
        self.widget_style_sheet.setObjectName("widget_style_sheet")
        self.layout_style_sheet = QtWidgets.QHBoxLayout(self.widget_style_sheet)
        self.layout_style_sheet.setContentsMargins(0, 0, 0, 0)
        self.layout_style_sheet.setSpacing(0)
        self.layout_style_sheet.setObjectName("layout_style_sheet")
        self.widget_menu = QtWidgets.QWidget(self.widget_style_sheet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_menu.sizePolicy().hasHeightForWidth())
        self.widget_menu.setSizePolicy(sizePolicy)
        self.widget_menu.setMinimumSize(QtCore.QSize(225, 0))
        self.widget_menu.setMaximumSize(QtCore.QSize(215, 16777215))
        self.widget_menu.setStyleSheet("")
        self.widget_menu.setObjectName("widget_menu")
        self.layout_menu = QtWidgets.QVBoxLayout(self.widget_menu)
        self.layout_menu.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_menu.setContentsMargins(0, 0, 0, 0)
        self.layout_menu.setSpacing(0)
        self.layout_menu.setObjectName("layout_menu")
        self.widget_menu_title = QtWidgets.QWidget(self.widget_menu)
        self.widget_menu_title.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_menu_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_menu_title.setStyleSheet("")
        self.widget_menu_title.setObjectName("widget_menu_title")
        self.layout_menu_title = QtWidgets.QHBoxLayout(self.widget_menu_title)
        self.layout_menu_title.setContentsMargins(0, 0, 0, 0)
        self.layout_menu_title.setSpacing(0)
        self.layout_menu_title.setObjectName("layout_menu_title")
        self.label_imag_app = QtWidgets.QLabel(self.widget_menu_title)
        self.label_imag_app.setMinimumSize(QtCore.QSize(40, 40))
        self.label_imag_app.setMaximumSize(QtCore.QSize(54, 40))
        self.label_imag_app.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_imag_app.setStyleSheet("padding-left: 7px;\n"
"padding-right: 7px;\n"
"border: none;\n"
"")
        self.label_imag_app.setText("")
        self.label_imag_app.setPixmap(QtGui.QPixmap(":/application_picture/resource/application_picture/app_icon-round.png"))
        self.label_imag_app.setScaledContents(True)
        self.label_imag_app.setIndent(-1)
        self.label_imag_app.setObjectName("label_imag_app")
        self.layout_menu_title.addWidget(self.label_imag_app)
        self.label_text_app_name = QtWidgets.QLabel(self.widget_menu_title)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_text_app_name.setFont(font)
        self.label_text_app_name.setStyleSheet("font-size: 14pt;")
        self.label_text_app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_app_name.setObjectName("label_text_app_name")
        self.layout_menu_title.addWidget(self.label_text_app_name)
        self.checkBox_color_theme = QtWidgets.QCheckBox(self.widget_menu_title)
        self.checkBox_color_theme.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_color_theme.setMaximumSize(QtCore.QSize(55, 16777215))
        self.checkBox_color_theme.setStyleSheet("/* Состояние - не выбран*/\n"
"QCheckBox::indicator:unchecked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/toggle_color_theme/resource/toggle_color_theme/off_black.svg);\n"
"\n"
"}\n"
"\n"
"/* Состояние -  выбран*/\n"
"QCheckBox::indicator:checked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/toggle_color_theme/resource/toggle_color_theme/on_white.svg);\n"
"}\n"
"")
        self.checkBox_color_theme.setText("")
        self.checkBox_color_theme.setObjectName("checkBox_color_theme")
        self.layout_menu_title.addWidget(self.checkBox_color_theme)
        self.layout_menu.addWidget(self.widget_menu_title)
        self.widget_menu_body = QtWidgets.QWidget(self.widget_menu)
        self.widget_menu_body.setStyleSheet(" .QWidget{\n"
"\n"
"}")
        self.widget_menu_body.setObjectName("widget_menu_body")
        self.layout_menu_body = QtWidgets.QVBoxLayout(self.widget_menu_body)
        self.layout_menu_body.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.layout_menu_body.setContentsMargins(0, 0, 3, 0)
        self.layout_menu_body.setSpacing(0)
        self.layout_menu_body.setObjectName("layout_menu_body")
        self.scrollArea_menu_body = QtWidgets.QScrollArea(self.widget_menu_body)
        self.scrollArea_menu_body.setTabletTracking(False)
        self.scrollArea_menu_body.setStyleSheet("")
        self.scrollArea_menu_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_menu_body.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_menu_body.setLineWidth(1)
        self.scrollArea_menu_body.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_menu_body.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_menu_body.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_menu_body.setWidgetResizable(True)
        self.scrollArea_menu_body.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_menu_body.setObjectName("scrollArea_menu_body")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 232, 496))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Layout_scroll_menu = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.Layout_scroll_menu.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Layout_scroll_menu.setContentsMargins(0, 0, 0, 0)
        self.Layout_scroll_menu.setSpacing(5)
        self.Layout_scroll_menu.setObjectName("Layout_scroll_menu")
        self.widget_neural_network = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_neural_network.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_neural_network.sizePolicy().hasHeightForWidth())
        self.widget_neural_network.setSizePolicy(sizePolicy)
        self.widget_neural_network.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_neural_network.setStyleSheet("")
        self.widget_neural_network.setObjectName("widget_neural_network")
        self.layout_menu_neural_network = QtWidgets.QVBoxLayout(self.widget_neural_network)
        self.layout_menu_neural_network.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_menu_neural_network.setContentsMargins(0, 0, 0, 5)
        self.layout_menu_neural_network.setSpacing(0)
        self.layout_menu_neural_network.setObjectName("layout_menu_neural_network")
        self.widget_neural_network_header = QtWidgets.QWidget(self.widget_neural_network)
        self.widget_neural_network_header.setStyleSheet("")
        self.widget_neural_network_header.setObjectName("widget_neural_network_header")
        self.layout_neural_network_header = QtWidgets.QHBoxLayout(self.widget_neural_network_header)
        self.layout_neural_network_header.setContentsMargins(0, 0, 0, 0)
        self.layout_neural_network_header.setSpacing(0)
        self.layout_neural_network_header.setObjectName("layout_neural_network_header")
        self.pushButton_neural_network_heade = QtWidgets.QPushButton(self.widget_neural_network_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_neural_network_heade.sizePolicy().hasHeightForWidth())
        self.pushButton_neural_network_heade.setSizePolicy(sizePolicy)
        self.pushButton_neural_network_heade.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_neural_network_heade.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_neural_network_heade.setFont(font)
        self.pushButton_neural_network_heade.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_neural_network_heade.setAccessibleDescription("")
        self.pushButton_neural_network_heade.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_neural_network_heade.setAutoFillBackground(False)
        self.pushButton_neural_network_heade.setStyleSheet("")
        self.pushButton_neural_network_heade.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_neural_network_heade.setCheckable(True)
        self.pushButton_neural_network_heade.setChecked(True)
        self.pushButton_neural_network_heade.setAutoRepeat(False)
        self.pushButton_neural_network_heade.setAutoExclusive(False)
        self.pushButton_neural_network_heade.setDefault(False)
        self.pushButton_neural_network_heade.setFlat(False)
        self.pushButton_neural_network_heade.setObjectName("pushButton_neural_network_heade")
        self.layout_neural_network_header.addWidget(self.pushButton_neural_network_heade)
        self.layout_menu_neural_network.addWidget(self.widget_neural_network_header)
        self.widget_neural_network_body = QtWidgets.QWidget(self.widget_neural_network)
        self.widget_neural_network_body.setEnabled(True)
        self.widget_neural_network_body.setStyleSheet("")
        self.widget_neural_network_body.setObjectName("widget_neural_network_body")
        self.layout_neural_network_body = QtWidgets.QVBoxLayout(self.widget_neural_network_body)
        self.layout_neural_network_body.setContentsMargins(5, 5, 5, 5)
        self.layout_neural_network_body.setSpacing(0)
        self.layout_neural_network_body.setObjectName("layout_neural_network_body")
        self.widget = QtWidgets.QWidget(self.widget_neural_network_body)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_text_neural_network = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_neural_network.sizePolicy().hasHeightForWidth())
        self.label_text_neural_network.setSizePolicy(sizePolicy)
        self.label_text_neural_network.setMinimumSize(QtCore.QSize(0, 30))
        self.label_text_neural_network.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_neural_network.setFont(font)
        self.label_text_neural_network.setStyleSheet("")
        self.label_text_neural_network.setTextFormat(QtCore.Qt.AutoText)
        self.label_text_neural_network.setScaledContents(False)
        self.label_text_neural_network.setObjectName("label_text_neural_network")
        self.horizontalLayout_2.addWidget(self.label_text_neural_network)
        self.pushButton_reading_file_neural_network = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reading_file_neural_network.sizePolicy().hasHeightForWidth())
        self.pushButton_reading_file_neural_network.setSizePolicy(sizePolicy)
        self.pushButton_reading_file_neural_network.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_reading_file_neural_network.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_reading_file_neural_network.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reading_file_neural_network.setWhatsThis("")
        self.pushButton_reading_file_neural_network.setAccessibleName("")
        self.pushButton_reading_file_neural_network.setAccessibleDescription("")
        self.pushButton_reading_file_neural_network.setStyleSheet("")
        self.pushButton_reading_file_neural_network.setText("")
        self.pushButton_reading_file_neural_network.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_reading_file_neural_network.setObjectName("pushButton_reading_file_neural_network")
        self.horizontalLayout_2.addWidget(self.pushButton_reading_file_neural_network)
        self.checkBox_download_neural_network = QtWidgets.QCheckBox(self.widget)
        self.checkBox_download_neural_network.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_download_neural_network.sizePolicy().hasHeightForWidth())
        self.checkBox_download_neural_network.setSizePolicy(sizePolicy)
        self.checkBox_download_neural_network.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_download_neural_network.setMaximumSize(QtCore.QSize(16777215, 30))
        self.checkBox_download_neural_network.setWhatsThis("")
        self.checkBox_download_neural_network.setAccessibleName("")
        self.checkBox_download_neural_network.setAccessibleDescription("")
        self.checkBox_download_neural_network.setStyleSheet("")
        self.checkBox_download_neural_network.setText("")
        self.checkBox_download_neural_network.setChecked(False)
        self.checkBox_download_neural_network.setTristate(False)
        self.checkBox_download_neural_network.setObjectName("checkBox_download_neural_network")
        self.horizontalLayout_2.addWidget(self.checkBox_download_neural_network)
        self.layout_neural_network_body.addWidget(self.widget)
        self.label_parameters_neural_network = QtWidgets.QLabel(self.widget_neural_network_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_parameters_neural_network.sizePolicy().hasHeightForWidth())
        self.label_parameters_neural_network.setSizePolicy(sizePolicy)
        self.label_parameters_neural_network.setText("")
        self.label_parameters_neural_network.setObjectName("label_parameters_neural_network")
        self.layout_neural_network_body.addWidget(self.label_parameters_neural_network)
        self.layout_menu_neural_network.addWidget(self.widget_neural_network_body)
        self.Layout_scroll_menu.addWidget(self.widget_neural_network)
        self.widget_data = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_data.sizePolicy().hasHeightForWidth())
        self.widget_data.setSizePolicy(sizePolicy)
        self.widget_data.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_data.setStyleSheet("")
        self.widget_data.setObjectName("widget_data")
        self.layout_menu_data = QtWidgets.QVBoxLayout(self.widget_data)
        self.layout_menu_data.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_menu_data.setContentsMargins(0, 0, 0, 5)
        self.layout_menu_data.setSpacing(0)
        self.layout_menu_data.setObjectName("layout_menu_data")
        self.widget_data_header = QtWidgets.QWidget(self.widget_data)
        self.widget_data_header.setStyleSheet("")
        self.widget_data_header.setObjectName("widget_data_header")
        self.layout_data_header = QtWidgets.QHBoxLayout(self.widget_data_header)
        self.layout_data_header.setContentsMargins(0, 0, 0, 0)
        self.layout_data_header.setSpacing(0)
        self.layout_data_header.setObjectName("layout_data_header")
        self.pushButton_data_header = QtWidgets.QPushButton(self.widget_data_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_data_header.sizePolicy().hasHeightForWidth())
        self.pushButton_data_header.setSizePolicy(sizePolicy)
        self.pushButton_data_header.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_data_header.setMaximumSize(QtCore.QSize(16777215, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_data_header.setFont(font)
        self.pushButton_data_header.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_data_header.setAccessibleDescription("")
        self.pushButton_data_header.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_data_header.setAutoFillBackground(False)
        self.pushButton_data_header.setStyleSheet("")
        self.pushButton_data_header.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_data_header.setCheckable(True)
        self.pushButton_data_header.setChecked(True)
        self.pushButton_data_header.setAutoRepeat(False)
        self.pushButton_data_header.setAutoExclusive(False)
        self.pushButton_data_header.setDefault(False)
        self.pushButton_data_header.setFlat(False)
        self.pushButton_data_header.setObjectName("pushButton_data_header")
        self.layout_data_header.addWidget(self.pushButton_data_header)
        self.layout_menu_data.addWidget(self.widget_data_header)
        self.widget_data_body = QtWidgets.QWidget(self.widget_data)
        self.widget_data_body.setStyleSheet("")
        self.widget_data_body.setObjectName("widget_data_body")
        self.layout_data_body = QtWidgets.QVBoxLayout(self.widget_data_body)
        self.layout_data_body.setContentsMargins(5, 5, 5, 5)
        self.layout_data_body.setSpacing(5)
        self.layout_data_body.setObjectName("layout_data_body")
        self.groupBox_no_gas = QtWidgets.QGroupBox(self.widget_data_body)
        self.groupBox_no_gas.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_no_gas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_no_gas.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_no_gas.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_no_gas.setFont(font)
        self.groupBox_no_gas.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_no_gas.setMouseTracking(False)
        self.groupBox_no_gas.setTabletTracking(False)
        self.groupBox_no_gas.setStyleSheet("")
        self.groupBox_no_gas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_no_gas.setFlat(True)
        self.groupBox_no_gas.setCheckable(False)
        self.groupBox_no_gas.setObjectName("groupBox_no_gas")
        self.layout_no_gas = QtWidgets.QHBoxLayout(self.groupBox_no_gas)
        self.layout_no_gas.setContentsMargins(5, 5, 5, 5)
        self.layout_no_gas.setSpacing(0)
        self.layout_no_gas.setObjectName("layout_no_gas")
        self.label_text_file_name_no_gas = QtWidgets.QLabel(self.groupBox_no_gas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_file_name_no_gas.sizePolicy().hasHeightForWidth())
        self.label_text_file_name_no_gas.setSizePolicy(sizePolicy)
        self.label_text_file_name_no_gas.setMinimumSize(QtCore.QSize(0, 30))
        self.label_text_file_name_no_gas.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_file_name_no_gas.setFont(font)
        self.label_text_file_name_no_gas.setStyleSheet("")
        self.label_text_file_name_no_gas.setTextFormat(QtCore.Qt.AutoText)
        self.label_text_file_name_no_gas.setScaledContents(False)
        self.label_text_file_name_no_gas.setObjectName("label_text_file_name_no_gas")
        self.layout_no_gas.addWidget(self.label_text_file_name_no_gas)
        self.pushButton_reading_file_no_gas = QtWidgets.QPushButton(self.groupBox_no_gas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reading_file_no_gas.sizePolicy().hasHeightForWidth())
        self.pushButton_reading_file_no_gas.setSizePolicy(sizePolicy)
        self.pushButton_reading_file_no_gas.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_reading_file_no_gas.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_reading_file_no_gas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reading_file_no_gas.setWhatsThis("")
        self.pushButton_reading_file_no_gas.setAccessibleName("")
        self.pushButton_reading_file_no_gas.setAccessibleDescription("")
        self.pushButton_reading_file_no_gas.setStyleSheet("")
        self.pushButton_reading_file_no_gas.setText("")
        self.pushButton_reading_file_no_gas.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_reading_file_no_gas.setObjectName("pushButton_reading_file_no_gas")
        self.layout_no_gas.addWidget(self.pushButton_reading_file_no_gas)
        self.checkBox_download_no_gas = QtWidgets.QCheckBox(self.groupBox_no_gas)
        self.checkBox_download_no_gas.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_download_no_gas.sizePolicy().hasHeightForWidth())
        self.checkBox_download_no_gas.setSizePolicy(sizePolicy)
        self.checkBox_download_no_gas.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_download_no_gas.setMaximumSize(QtCore.QSize(16777215, 30))
        self.checkBox_download_no_gas.setWhatsThis("")
        self.checkBox_download_no_gas.setAccessibleName("")
        self.checkBox_download_no_gas.setAccessibleDescription("")
        self.checkBox_download_no_gas.setStyleSheet("")
        self.checkBox_download_no_gas.setText("")
        self.checkBox_download_no_gas.setChecked(False)
        self.checkBox_download_no_gas.setTristate(False)
        self.checkBox_download_no_gas.setObjectName("checkBox_download_no_gas")
        self.layout_no_gas.addWidget(self.checkBox_download_no_gas)
        self.layout_data_body.addWidget(self.groupBox_no_gas)
        self.groupBox_with_gas = QtWidgets.QGroupBox(self.widget_data_body)
        self.groupBox_with_gas.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_with_gas.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_with_gas.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_with_gas.setFont(font)
        self.groupBox_with_gas.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_with_gas.setMouseTracking(False)
        self.groupBox_with_gas.setTabletTracking(False)
        self.groupBox_with_gas.setStyleSheet("")
        self.groupBox_with_gas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_with_gas.setFlat(True)
        self.groupBox_with_gas.setCheckable(False)
        self.groupBox_with_gas.setObjectName("groupBox_with_gas")
        self.layout_with_gas = QtWidgets.QHBoxLayout(self.groupBox_with_gas)
        self.layout_with_gas.setContentsMargins(5, 5, 5, 5)
        self.layout_with_gas.setSpacing(0)
        self.layout_with_gas.setObjectName("layout_with_gas")
        self.label_text_file_name_with_gas = QtWidgets.QLabel(self.groupBox_with_gas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_file_name_with_gas.sizePolicy().hasHeightForWidth())
        self.label_text_file_name_with_gas.setSizePolicy(sizePolicy)
        self.label_text_file_name_with_gas.setMinimumSize(QtCore.QSize(0, 30))
        self.label_text_file_name_with_gas.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_file_name_with_gas.setFont(font)
        self.label_text_file_name_with_gas.setStyleSheet("")
        self.label_text_file_name_with_gas.setTextFormat(QtCore.Qt.AutoText)
        self.label_text_file_name_with_gas.setScaledContents(False)
        self.label_text_file_name_with_gas.setObjectName("label_text_file_name_with_gas")
        self.layout_with_gas.addWidget(self.label_text_file_name_with_gas)
        self.pushButton_reading_file_with_gas = QtWidgets.QPushButton(self.groupBox_with_gas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reading_file_with_gas.sizePolicy().hasHeightForWidth())
        self.pushButton_reading_file_with_gas.setSizePolicy(sizePolicy)
        self.pushButton_reading_file_with_gas.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_reading_file_with_gas.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_reading_file_with_gas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reading_file_with_gas.setStyleSheet("")
        self.pushButton_reading_file_with_gas.setText("")
        self.pushButton_reading_file_with_gas.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_reading_file_with_gas.setObjectName("pushButton_reading_file_with_gas")
        self.layout_with_gas.addWidget(self.pushButton_reading_file_with_gas)
        self.checkBox_download_with_gas = QtWidgets.QCheckBox(self.groupBox_with_gas)
        self.checkBox_download_with_gas.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_download_with_gas.sizePolicy().hasHeightForWidth())
        self.checkBox_download_with_gas.setSizePolicy(sizePolicy)
        self.checkBox_download_with_gas.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_download_with_gas.setMaximumSize(QtCore.QSize(16777215, 30))
        self.checkBox_download_with_gas.setStyleSheet("")
        self.checkBox_download_with_gas.setText("")
        self.checkBox_download_with_gas.setChecked(False)
        self.checkBox_download_with_gas.setTristate(False)
        self.checkBox_download_with_gas.setObjectName("checkBox_download_with_gas")
        self.layout_with_gas.addWidget(self.checkBox_download_with_gas)
        self.layout_data_body.addWidget(self.groupBox_with_gas)
        self.pushButton_reset_spectrum_data = QtWidgets.QPushButton(self.widget_data_body)
        self.pushButton_reset_spectrum_data.setMinimumSize(QtCore.QSize(142, 0))
        self.pushButton_reset_spectrum_data.setMaximumSize(QtCore.QSize(142, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_reset_spectrum_data.setFont(font)
        self.pushButton_reset_spectrum_data.setStyleSheet("QPushButton:hover {\n"
"    border: none;                                                /* без границ */\n"
"}")
        self.pushButton_reset_spectrum_data.setObjectName("pushButton_reset_spectrum_data")
        self.layout_data_body.addWidget(self.pushButton_reset_spectrum_data, 0, QtCore.Qt.AlignHCenter)
        self.groupBox_frequency_range = QtWidgets.QGroupBox(self.widget_data_body)
        self.groupBox_frequency_range.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_frequency_range.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_frequency_range.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_frequency_range.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_frequency_range.setFont(font)
        self.groupBox_frequency_range.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_frequency_range.setMouseTracking(False)
        self.groupBox_frequency_range.setTabletTracking(False)
        self.groupBox_frequency_range.setStyleSheet("")
        self.groupBox_frequency_range.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_frequency_range.setFlat(True)
        self.groupBox_frequency_range.setCheckable(False)
        self.groupBox_frequency_range.setObjectName("groupBox_frequency_range")
        self.layout_frequency_range = QtWidgets.QVBoxLayout(self.groupBox_frequency_range)
        self.layout_frequency_range.setContentsMargins(5, 5, 5, 5)
        self.layout_frequency_range.setSpacing(0)
        self.layout_frequency_range.setObjectName("layout_frequency_range")
        self.radioButton_all_range = QtWidgets.QRadioButton(self.groupBox_frequency_range)
        self.radioButton_all_range.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_all_range.setFont(font)
        self.radioButton_all_range.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_all_range.setStyleSheet("")
        self.radioButton_all_range.setChecked(True)
        self.radioButton_all_range.setObjectName("radioButton_all_range")
        self.layout_frequency_range.addWidget(self.radioButton_all_range)
        self.radioButton_selected_range = QtWidgets.QRadioButton(self.groupBox_frequency_range)
        self.radioButton_selected_range.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_selected_range.setFont(font)
        self.radioButton_selected_range.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_selected_range.setStyleSheet("")
        self.radioButton_selected_range.setChecked(False)
        self.radioButton_selected_range.setObjectName("radioButton_selected_range")
        self.layout_frequency_range.addWidget(self.radioButton_selected_range)
        self.widget_start_range = QtWidgets.QWidget(self.groupBox_frequency_range)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_start_range.sizePolicy().hasHeightForWidth())
        self.widget_start_range.setSizePolicy(sizePolicy)
        self.widget_start_range.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_start_range.setStyleSheet("")
        self.widget_start_range.setObjectName("widget_start_range")
        self.layout_start_range = QtWidgets.QHBoxLayout(self.widget_start_range)
        self.layout_start_range.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_start_range.setContentsMargins(0, 0, 0, 0)
        self.layout_start_range.setSpacing(0)
        self.layout_start_range.setObjectName("layout_start_range")
        self.label_text_start_range = QtWidgets.QLabel(self.widget_start_range)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_start_range.sizePolicy().hasHeightForWidth())
        self.label_text_start_range.setSizePolicy(sizePolicy)
        self.label_text_start_range.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_start_range.setFont(font)
        self.label_text_start_range.setObjectName("label_text_start_range")
        self.layout_start_range.addWidget(self.label_text_start_range)
        self.lineEdit_start_range = QtWidgets.QLineEdit(self.widget_start_range)
        self.lineEdit_start_range.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_start_range.sizePolicy().hasHeightForWidth())
        self.lineEdit_start_range.setSizePolicy(sizePolicy)
        self.lineEdit_start_range.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_start_range.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_start_range.setFont(font)
        self.lineEdit_start_range.setStyleSheet("")
        self.lineEdit_start_range.setText("22308")
        self.lineEdit_start_range.setMaxLength(10)
        self.lineEdit_start_range.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_start_range.setDragEnabled(False)
        self.lineEdit_start_range.setObjectName("lineEdit_start_range")
        self.layout_start_range.addWidget(self.lineEdit_start_range)
        self.label_text_units_start_range = QtWidgets.QLabel(self.widget_start_range)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_units_start_range.sizePolicy().hasHeightForWidth())
        self.label_text_units_start_range.setSizePolicy(sizePolicy)
        self.label_text_units_start_range.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_units_start_range.setFont(font)
        self.label_text_units_start_range.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_units_start_range.setObjectName("label_text_units_start_range")
        self.layout_start_range.addWidget(self.label_text_units_start_range)
        self.layout_frequency_range.addWidget(self.widget_start_range)
        self.widget_end_range = QtWidgets.QWidget(self.groupBox_frequency_range)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_end_range.sizePolicy().hasHeightForWidth())
        self.widget_end_range.setSizePolicy(sizePolicy)
        self.widget_end_range.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_end_range.setStyleSheet("")
        self.widget_end_range.setObjectName("widget_end_range")
        self.layout_end_range = QtWidgets.QHBoxLayout(self.widget_end_range)
        self.layout_end_range.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_end_range.setContentsMargins(0, 0, 0, 0)
        self.layout_end_range.setSpacing(0)
        self.layout_end_range.setObjectName("layout_end_range")
        self.label_text_end_range = QtWidgets.QLabel(self.widget_end_range)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_end_range.sizePolicy().hasHeightForWidth())
        self.label_text_end_range.setSizePolicy(sizePolicy)
        self.label_text_end_range.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_end_range.setFont(font)
        self.label_text_end_range.setStyleSheet("")
        self.label_text_end_range.setObjectName("label_text_end_range")
        self.layout_end_range.addWidget(self.label_text_end_range)
        self.lineEdit_end_range = QtWidgets.QLineEdit(self.widget_end_range)
        self.lineEdit_end_range.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_end_range.sizePolicy().hasHeightForWidth())
        self.lineEdit_end_range.setSizePolicy(sizePolicy)
        self.lineEdit_end_range.setMinimumSize(QtCore.QSize(120, 30))
        self.lineEdit_end_range.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_end_range.setFont(font)
        self.lineEdit_end_range.setStyleSheet("")
        self.lineEdit_end_range.setText("22342")
        self.lineEdit_end_range.setMaxLength(10)
        self.lineEdit_end_range.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_end_range.setDragEnabled(False)
        self.lineEdit_end_range.setObjectName("lineEdit_end_range")
        self.layout_end_range.addWidget(self.lineEdit_end_range)
        self.label_text_units_end_range = QtWidgets.QLabel(self.widget_end_range)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_units_end_range.sizePolicy().hasHeightForWidth())
        self.label_text_units_end_range.setSizePolicy(sizePolicy)
        self.label_text_units_end_range.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_text_units_end_range.setFont(font)
        self.label_text_units_end_range.setStyleSheet("")
        self.label_text_units_end_range.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_units_end_range.setObjectName("label_text_units_end_range")
        self.layout_end_range.addWidget(self.label_text_units_end_range)
        self.layout_frequency_range.addWidget(self.widget_end_range)
        self.layout_data_body.addWidget(self.groupBox_frequency_range)
        self.layout_menu_data.addWidget(self.widget_data_body)
        self.Layout_scroll_menu.addWidget(self.widget_data)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Layout_scroll_menu.addItem(spacerItem)
        self.scrollArea_menu_body.setWidget(self.scrollAreaWidgetContents)
        self.layout_menu_body.addWidget(self.scrollArea_menu_body)
        self.layout_menu.addWidget(self.widget_menu_body)
        self.widget_menu_bottom = QtWidgets.QWidget(self.widget_menu)
        self.widget_menu_bottom.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_menu_bottom.setStyleSheet("QWidget#widget_menu_bottom{\n"
"    border: none;                                                /* без границ */\n"
"    border-top:2px solid rgb(255, 255, 255);    /* С правой красной раницей */\n"
"}")
        self.widget_menu_bottom.setObjectName("widget_menu_bottom")
        self.layout_menu_bottom = QtWidgets.QVBoxLayout(self.widget_menu_bottom)
        self.layout_menu_bottom.setContentsMargins(0, 5, 0, 0)
        self.layout_menu_bottom.setSpacing(2)
        self.layout_menu_bottom.setObjectName("layout_menu_bottom")
        self.pushButton_close_open_table = QtWidgets.QPushButton(self.widget_menu_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close_open_table.sizePolicy().hasHeightForWidth())
        self.pushButton_close_open_table.setSizePolicy(sizePolicy)
        self.pushButton_close_open_table.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_close_open_table.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_open_table.setFont(font)
        self.pushButton_close_open_table.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_open_table.setAccessibleDescription("")
        self.pushButton_close_open_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_close_open_table.setAutoFillBackground(False)
        self.pushButton_close_open_table.setStyleSheet("")
        self.pushButton_close_open_table.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_close_open_table.setCheckable(True)
        self.pushButton_close_open_table.setChecked(True)
        self.pushButton_close_open_table.setAutoRepeat(False)
        self.pushButton_close_open_table.setAutoExclusive(False)
        self.pushButton_close_open_table.setDefault(False)
        self.pushButton_close_open_table.setFlat(False)
        self.pushButton_close_open_table.setObjectName("pushButton_close_open_table")
        self.layout_menu_bottom.addWidget(self.pushButton_close_open_table)
        self.pushButton_menu_calculate = QtWidgets.QPushButton(self.widget_menu_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_menu_calculate.sizePolicy().hasHeightForWidth())
        self.pushButton_menu_calculate.setSizePolicy(sizePolicy)
        self.pushButton_menu_calculate.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_menu_calculate.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_menu_calculate.setFont(font)
        self.pushButton_menu_calculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_menu_calculate.setAccessibleDescription("")
        self.pushButton_menu_calculate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_menu_calculate.setAutoFillBackground(False)
        self.pushButton_menu_calculate.setStyleSheet("")
        self.pushButton_menu_calculate.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_menu_calculate.setCheckable(True)
        self.pushButton_menu_calculate.setChecked(True)
        self.pushButton_menu_calculate.setAutoRepeat(False)
        self.pushButton_menu_calculate.setAutoExclusive(False)
        self.pushButton_menu_calculate.setDefault(False)
        self.pushButton_menu_calculate.setFlat(False)
        self.pushButton_menu_calculate.setObjectName("pushButton_menu_calculate")
        self.layout_menu_bottom.addWidget(self.pushButton_menu_calculate)
        self.layout_menu.addWidget(self.widget_menu_bottom)
        self.layout_style_sheet.addWidget(self.widget_menu)
        self.widget_main = QtWidgets.QWidget(self.widget_style_sheet)
        self.widget_main.setStyleSheet("")
        self.widget_main.setObjectName("widget_main")
        self.layout_main = QtWidgets.QVBoxLayout(self.widget_main)
        self.layout_main.setContentsMargins(0, 0, 0, 0)
        self.layout_main.setSpacing(0)
        self.layout_main.setObjectName("layout_main")
        self.widget_main_body = QtWidgets.QWidget(self.widget_main)
        self.widget_main_body.setStyleSheet("")
        self.widget_main_body.setObjectName("widget_main_body")
        self.layout__main_body = QtWidgets.QHBoxLayout(self.widget_main_body)
        self.layout__main_body.setContentsMargins(0, 0, 0, 0)
        self.layout__main_body.setSpacing(0)
        self.layout__main_body.setObjectName("layout__main_body")
        self.widget_plotting = QtWidgets.QWidget(self.widget_main_body)
        self.widget_plotting.setStyleSheet("QWidget{\n"
"background-color: rgb(240, 240, 240);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.widget_plotting.setObjectName("widget_plotting")
        self.layout_plotting = QtWidgets.QVBoxLayout(self.widget_plotting)
        self.layout_plotting.setContentsMargins(0, 0, 0, 0)
        self.layout_plotting.setSpacing(0)
        self.layout_plotting.setObjectName("layout_plotting")
        self.widget_plot_1 = QtWidgets.QWidget(self.widget_plotting)
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.layout_plot_1 = QtWidgets.QVBoxLayout(self.widget_plot_1)
        self.layout_plot_1.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_1.setSpacing(0)
        self.layout_plot_1.setObjectName("layout_plot_1")
        self.layout_plotting.addWidget(self.widget_plot_1)
        self.layout__main_body.addWidget(self.widget_plotting)
        self.widget_right = QtWidgets.QWidget(self.widget_main_body)
        self.widget_right.setMinimumSize(QtCore.QSize(260, 0))
        self.widget_right.setStyleSheet("")
        self.widget_right.setObjectName("widget_right")
        self.layout_right = QtWidgets.QHBoxLayout(self.widget_right)
        self.layout_right.setContentsMargins(0, 0, 0, 0)
        self.layout_right.setSpacing(0)
        self.layout_right.setObjectName("layout_right")
        self.widget_table = QtWidgets.QWidget(self.widget_right)
        self.widget_table.setStyleSheet("/* Состояние - не выбран*/\n"
"QCheckBox::indicator:unchecked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/table_checkbox/resource/table_checkbox/var2_color/no_red_24dp.svg);\n"
"}\n"
"\n"
"/* Состояние -  выбран*/\n"
"QCheckBox::indicator:checked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/table_checkbox/resource/table_checkbox/var2_color/yes_green_24dp.svg);\n"
"}\n"
"")
        self.widget_table.setObjectName("widget_table")
        self.layout_table = QtWidgets.QVBoxLayout(self.widget_table)
        self.layout_table.setContentsMargins(2, 0, 0, 0)
        self.layout_table.setSpacing(0)
        self.layout_table.setObjectName("layout_table")
        self.widget_table_view_mode = QtWidgets.QWidget(self.widget_table)
        self.widget_table_view_mode.setObjectName("widget_table_view_mode")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_table_view_mode)
        self.horizontalLayout.setContentsMargins(2, 2, 0, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_text_select_table_display = QtWidgets.QLabel(self.widget_table_view_mode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_select_table_display.sizePolicy().hasHeightForWidth())
        self.label_text_select_table_display.setSizePolicy(sizePolicy)
        self.label_text_select_table_display.setObjectName("label_text_select_table_display")
        self.horizontalLayout.addWidget(self.label_text_select_table_display)
        self.comboBox_select_table_view = QtWidgets.QComboBox(self.widget_table_view_mode)
        self.comboBox_select_table_view.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_select_table_view.setStyleSheet("QWidget{\n"
"selection-background-color: rgb(191, 191, 191);\n"
"\n"
"}")
        self.comboBox_select_table_view.setCurrentText("")
        self.comboBox_select_table_view.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_select_table_view.setIconSize(QtCore.QSize(20, 20))
        self.comboBox_select_table_view.setObjectName("comboBox_select_table_view")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/multi_check_box/resource/multi_check_box_svg/all_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_select_table_view.addItem(icon1, "")
        self.comboBox_select_table_view.setItemText(0, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/multi_check_box/resource/multi_check_box_svg/undefined_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_select_table_view.addItem(icon2, "")
        self.comboBox_select_table_view.setItemText(1, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/multi_check_box/resource/multi_check_box_svg/no_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_select_table_view.addItem(icon3, "")
        self.comboBox_select_table_view.setItemText(2, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/multi_check_box/resource/multi_check_box_svg/yes_green_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_select_table_view.addItem(icon4, "")
        self.comboBox_select_table_view.setItemText(3, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/multi_check_box/resource/multi_check_box_svg/yes_blue_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_select_table_view.addItem(icon5, "")
        self.comboBox_select_table_view.setItemText(4, "")
        self.horizontalLayout.addWidget(self.comboBox_select_table_view)
        self.layout_table.addWidget(self.widget_table_view_mode)
        self.tableWidget_frequency_absorption = QtWidgets.QTableWidget(self.widget_table)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_frequency_absorption.sizePolicy().hasHeightForWidth())
        self.tableWidget_frequency_absorption.setSizePolicy(sizePolicy)
        self.tableWidget_frequency_absorption.setStyleSheet("")
        self.tableWidget_frequency_absorption.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_frequency_absorption.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_frequency_absorption.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_frequency_absorption.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_frequency_absorption.setTabKeyNavigation(False)
        self.tableWidget_frequency_absorption.setProperty("showDropIndicator", False)
        self.tableWidget_frequency_absorption.setDragDropOverwriteMode(False)
        self.tableWidget_frequency_absorption.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_frequency_absorption.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_frequency_absorption.setIconSize(QtCore.QSize(0, 0))
        self.tableWidget_frequency_absorption.setShowGrid(True)
        self.tableWidget_frequency_absorption.setRowCount(0)
        self.tableWidget_frequency_absorption.setColumnCount(0)
        self.tableWidget_frequency_absorption.setObjectName("tableWidget_frequency_absorption")
        self.tableWidget_frequency_absorption.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_frequency_absorption.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_frequency_absorption.horizontalHeader().setStretchLastSection(False)
        self.layout_table.addWidget(self.tableWidget_frequency_absorption)
        self.widget_bottom = QtWidgets.QWidget(self.widget_table)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_bottom.sizePolicy().hasHeightForWidth())
        self.widget_bottom.setSizePolicy(sizePolicy)
        self.widget_bottom.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_bottom.setStyleSheet("")
        self.widget_bottom.setObjectName("widget_bottom")
        self.layout_bottom = QtWidgets.QVBoxLayout(self.widget_bottom)
        self.layout_bottom.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_bottom.setContentsMargins(0, 0, 0, 0)
        self.layout_bottom.setSpacing(0)
        self.layout_bottom.setObjectName("layout_bottom")
        self.label_statistics_on_selected_frequencies = QtWidgets.QLabel(self.widget_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_statistics_on_selected_frequencies.sizePolicy().hasHeightForWidth())
        self.label_statistics_on_selected_frequencies.setSizePolicy(sizePolicy)
        self.label_statistics_on_selected_frequencies.setMinimumSize(QtCore.QSize(0, 30))
        self.label_statistics_on_selected_frequencies.setStyleSheet("")
        self.label_statistics_on_selected_frequencies.setText("")
        self.label_statistics_on_selected_frequencies.setObjectName("label_statistics_on_selected_frequencies")
        self.layout_bottom.addWidget(self.label_statistics_on_selected_frequencies)
        self.groupBox_window_view = QtWidgets.QGroupBox(self.widget_bottom)
        self.groupBox_window_view.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox_window_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_window_view.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_window_view.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_window_view.setFont(font)
        self.groupBox_window_view.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_window_view.setMouseTracking(False)
        self.groupBox_window_view.setTabletTracking(False)
        self.groupBox_window_view.setStyleSheet("")
        self.groupBox_window_view.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_window_view.setFlat(True)
        self.groupBox_window_view.setCheckable(False)
        self.groupBox_window_view.setObjectName("groupBox_window_view")
        self.layout_frequency_range_3 = QtWidgets.QVBoxLayout(self.groupBox_window_view)
        self.layout_frequency_range_3.setContentsMargins(5, 0, 5, 0)
        self.layout_frequency_range_3.setSpacing(0)
        self.layout_frequency_range_3.setObjectName("layout_frequency_range_3")
        self.label_text_window_width = QtWidgets.QLabel(self.groupBox_window_view)
        self.label_text_window_width.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_window_width.setObjectName("label_text_window_width")
        self.layout_frequency_range_3.addWidget(self.label_text_window_width)
        self.widget_input_window_view = QtWidgets.QWidget(self.groupBox_window_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_input_window_view.sizePolicy().hasHeightForWidth())
        self.widget_input_window_view.setSizePolicy(sizePolicy)
        self.widget_input_window_view.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_input_window_view.setStyleSheet("")
        self.widget_input_window_view.setObjectName("widget_input_window_view")
        self.layout_start_range_8 = QtWidgets.QHBoxLayout(self.widget_input_window_view)
        self.layout_start_range_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_start_range_8.setContentsMargins(0, 0, 0, 0)
        self.layout_start_range_8.setSpacing(0)
        self.layout_start_range_8.setObjectName("layout_start_range_8")
        self.lineEdit_window_width = QtWidgets.QLineEdit(self.widget_input_window_view)
        self.lineEdit_window_width.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_window_width.sizePolicy().hasHeightForWidth())
        self.lineEdit_window_width.setSizePolicy(sizePolicy)
        self.lineEdit_window_width.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_window_width.setMaximumSize(QtCore.QSize(120, 30))
        self.lineEdit_window_width.setStyleSheet("")
        self.lineEdit_window_width.setText("10")
        self.lineEdit_window_width.setMaxLength(10)
        self.lineEdit_window_width.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_window_width.setDragEnabled(False)
        self.lineEdit_window_width.setObjectName("lineEdit_window_width")
        self.layout_start_range_8.addWidget(self.lineEdit_window_width)
        self.label_text_units_window_width = QtWidgets.QLabel(self.widget_input_window_view)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_units_window_width.sizePolicy().hasHeightForWidth())
        self.label_text_units_window_width.setSizePolicy(sizePolicy)
        self.label_text_units_window_width.setMinimumSize(QtCore.QSize(0, 30))
        self.label_text_units_window_width.setStyleSheet("")
        self.label_text_units_window_width.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_units_window_width.setObjectName("label_text_units_window_width")
        self.layout_start_range_8.addWidget(self.label_text_units_window_width)
        self.layout_frequency_range_3.addWidget(self.widget_input_window_view)
        self.layout_bottom.addWidget(self.groupBox_window_view)
        self.pushButton_save_table_to_file = QtWidgets.QPushButton(self.widget_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_table_to_file.sizePolicy().hasHeightForWidth())
        self.pushButton_save_table_to_file.setSizePolicy(sizePolicy)
        self.pushButton_save_table_to_file.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_save_table_to_file.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save_table_to_file.setFont(font)
        self.pushButton_save_table_to_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_save_table_to_file.setAccessibleDescription("")
        self.pushButton_save_table_to_file.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_save_table_to_file.setAutoFillBackground(False)
        self.pushButton_save_table_to_file.setStyleSheet("")
        self.pushButton_save_table_to_file.setIconSize(QtCore.QSize(0, 0))
        self.pushButton_save_table_to_file.setCheckable(True)
        self.pushButton_save_table_to_file.setChecked(True)
        self.pushButton_save_table_to_file.setAutoRepeat(False)
        self.pushButton_save_table_to_file.setAutoExclusive(False)
        self.pushButton_save_table_to_file.setDefault(False)
        self.pushButton_save_table_to_file.setFlat(False)
        self.pushButton_save_table_to_file.setObjectName("pushButton_save_table_to_file")
        self.layout_bottom.addWidget(self.pushButton_save_table_to_file)
        self.layout_table.addWidget(self.widget_bottom)
        self.layout_right.addWidget(self.widget_table)
        self.layout__main_body.addWidget(self.widget_right)
        self.layout__main_body.setStretch(0, 1)
        self.layout_main.addWidget(self.widget_main_body)
        self.layout_style_sheet.addWidget(self.widget_main)
        self.layout_dialog_main.addWidget(self.widget_style_sheet)

        self.retranslateUi(Dialog)
        self.pushButton_data_header.clicked['bool'].connect(self.widget_data_body.setVisible) # type: ignore
        self.radioButton_selected_range.toggled['bool'].connect(self.lineEdit_start_range.setEnabled) # type: ignore
        self.radioButton_selected_range.toggled['bool'].connect(self.lineEdit_end_range.setEnabled) # type: ignore
        self.pushButton_close_open_table.clicked['bool'].connect(self.widget_right.setVisible) # type: ignore
        self.pushButton_neural_network_heade.toggled['bool'].connect(self.widget_neural_network_body.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Детектирование c использованием нейронной сети"))
        self.label_text_app_name.setText(_translate("Dialog", "Детектор"))
        self.pushButton_neural_network_heade.setText(_translate("Dialog", "Нейронная сеть"))
        self.label_text_neural_network.setText(_translate("Dialog", "Нет файла"))
        self.pushButton_data_header.setText(_translate("Dialog", "Данные"))
        self.groupBox_no_gas.setTitle(_translate("Dialog", "Без исследуемого вещества"))
        self.label_text_file_name_no_gas.setText(_translate("Dialog", "Нет файла"))
        self.groupBox_with_gas.setTitle(_translate("Dialog", "С исследуемым веществом"))
        self.label_text_file_name_with_gas.setText(_translate("Dialog", "Нет файла"))
        self.pushButton_reset_spectrum_data.setText(_translate("Dialog", "Сброс данных"))
        self.groupBox_frequency_range.setTitle(_translate("Dialog", "Диапазон частот"))
        self.radioButton_all_range.setText(_translate("Dialog", "Весь"))
        self.radioButton_selected_range.setText(_translate("Dialog", "Некоторые"))
        self.label_text_start_range.setText(_translate("Dialog", "От: "))
        self.label_text_units_start_range.setText(_translate("Dialog", " [МГц]"))
        self.label_text_end_range.setText(_translate("Dialog", "До: "))
        self.label_text_units_end_range.setText(_translate("Dialog", " [МГц]"))
        self.pushButton_close_open_table.setText(_translate("Dialog", "Таблица"))
        self.pushButton_menu_calculate.setText(_translate("Dialog", "Вычислить"))
        self.label_text_select_table_display.setText(_translate("Dialog", "Отображаемые данных: "))
        self.tableWidget_frequency_absorption.setSortingEnabled(False)
        self.groupBox_window_view.setTitle(_translate("Dialog", "Окно просмотра"))
        self.label_text_window_width.setText(_translate("Dialog", "Ширина окна просмотра \n"
" найденных частот"))
        self.label_text_units_window_width.setText(_translate("Dialog", " [МГц]"))
        self.pushButton_save_table_to_file.setText(_translate("Dialog", "Сохранить в файл"))
import res_rc
