import os

DEBUG_ALL: bool = os.getenv("DEBUG_ALL", False)
USE_DEFAULT_FILE_PATH_WITHOUT_SUBSTANCE: bool = os.getenv("USE_DEFAULT_FILE_PATH_WITHOUT_SUBSTANCE", False)
USE_DEFAULT_FILE_PATH_WITH_SUBSTANCE: bool = os.getenv("USE_DEFAULT_FILE_PATH_WITH_SUBSTANCE", False)
USE_DEFAULT_FILE_PATH_NEURAL_NETWORK: bool = os.getenv("USE_DEFAULT_FILE_PATH_NEURAL_NETWORK", False)
DEFAULT_FILE_PATH_WITHOUT_SUBSTANCE: str = "data/empty.csv"
DEFAULT_FILE_PATH_WITH_SUBSTANCE: str = "data/DMSO.csv"
DEFAULT_FILE_PATH_NEURAL_NETWORK: str = "data/5_new.joblib"
